In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [48]:
loan_data = pd.read_csv('./loan_data_set.csv')
loan_data.head(5)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [49]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [50]:
# Gender Column
loan_data['Gender'] =  loan_data['Gender'].map({'Male':0,'Female':1})

# Married column
loan_data['Married'] = loan_data['Married'].map({'No':0,'Yes':1})

# Loan_Status column
loan_data['Loan_Status'] =loan_data['Loan_Status'].map({'N':0,'Y':1})

In [51]:
loan_data['Gender'] = loan_data['Gender'].fillna(loan_data['Gender'].mode()[0])
loan_data['Married'] = loan_data['Married'].fillna(loan_data['Married'].mode()[0])
loan_data['Dependents'] = loan_data['Dependents'].fillna(loan_data['Dependents'].mode()[0])
loan_data['S    elf_Employed'].fillna('No',inplace=True)
loan_data['Credit_History'] = loan_data['Credit_History'].fillna(loan_data['Credit_History'].mode()[0])
loan_data['LoanAmount'] = loan_data['LoanAmount'].fillna(loan_data['LoanAmount'].median())
loan_data['Loan_Amount_Term'] = loan_data['Loan_Amount_Term'].fillna(loan_data['Loan_Amount_Term'].mode()[0])


KeyError: 'S    elf_Employed'

In [ ]:
X = loan_data[['Gender', 'Married', 'ApplicantIncome', 'LoanAmount',
'Credit_History']]
y = loan_data.Loan_Status

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_cv, y_train, y_cv = train_test_split(X,y, test_size = 0.2,random_state = 10)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
decision_tree = DecisionTreeClassifier()
decision_tree.fit(x_train, y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [52]:
import graphviz
from sklearn.tree import  export_graphviz

dot_data = export_graphviz(decision_tree, out_file=None, 
                           feature_names=x_train.columns,  
                           class_names=['N','Y'],  
                           filled=True, rounded=True,  
                           special_characters=True)

# Visualize the decision tree
graph = graphviz.Source(dot_data)
graph.render("decision_tree")

# Alternatively, you can save the decision tree as a PNG image directly
graph.format = 'png'
graph.render("decision_tree")

'decision_tree.png'

In [ ]:
from sklearn.ensemble import RandomForestClassifier,BaggingClassifier,AdaBoostClassifier

random_forest = RandomForestClassifier()
random_forest.fit(x_train, y_train)

bagging = BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=50, random_state=42)
bagging.fit(x_train, y_train)

# Adaboost
adaboost = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1), n_estimators=50, random_state=42)
adaboost.fit(x_train, y_train)


AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=1,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort='deprecated',
                          

In [ ]:
dt_pred = decision_tree.predict(x_cv)
rf_pred = random_forest.predict(x_cv)
bagging_pred = bagging.predict(x_cv)
adaboost_pred = adaboost.predict(x_cv)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix

dt_accuracy = accuracy_score(y_cv, dt_pred)
rf_accuracy = accuracy_score(y_cv, rf_pred)
bagging_accuracy = accuracy_score(y_cv, bagging_pred)
adaboost_accuracy = accuracy_score(y_cv, adaboost_pred)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(max_depth=4, random_state = 10)
model.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=4, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=10, verbose=0,
                       warm_start=False)

In [ ]:
dt_confusion_matrix = confusion_matrix(y_cv, dt_pred)
rf_confusion_matrix = confusion_matrix(y_cv, rf_pred)
bagging_confusion_matrix = confusion_matrix(y_cv, bagging_pred)
adaboost_confusion_matrix = confusion_matrix(y_cv, adaboost_pred)

In [ ]:
print("Decision Tree Accuracy:", dt_accuracy)
print("Random Forest Accuracy:", rf_accuracy)
print("Bagging Accuracy:", bagging_accuracy)
print("Adaboost Accuracy:", adaboost_accuracy)

print("\nDecision Tree Confusion Matrix:")
print(dt_confusion_matrix)
print("\nRandom Forest Confusion Matrix:")
print(rf_confusion_matrix)
print("\nBagging Confusion Matrix:")
print(bagging_confusion_matrix)
print("\nAdaboost Confusion Matrix:")
print(adaboost_confusion_matrix)


Decision Tree Accuracy: 0.6910569105691057
Random Forest Accuracy: 0.7804878048780488
Bagging Accuracy: 0.7723577235772358
Adaboost Accuracy: 0.7967479674796748

Decision Tree Confusion Matrix:
[[18 18]
 [20 67]]

Random Forest Confusion Matrix:
[[16 20]
 [ 7 80]]

Bagging Confusion Matrix:
[[15 21]
 [ 7 80]]

Adaboost Confusion Matrix:
[[13 23]
 [ 2 85]]


In [ ]:
from sklearn.metrics import accuracy_score
pred_cv = model.predict(x_cv)
accuracy_score(y_cv,pred_cv)

0.7967479674796748

In [ ]:
pred_train = model.predict(x_train)
print("Accuracy: ",accuracy_score(y_train,pred_train))

Accuracy:  0.8167006109979633


'decision_tree.png'